version: '3.8'


services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: perfStudy
      POSTGRES_PASSWORD: perfStudy
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql