---
# Metallb address pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-cluster-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.31.10.230 - 172.31.10.240
---
# L2 configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: test
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-cluster-pool